In [63]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [64]:
df=pd.read_csv('passengers.csv')

In [66]:
df.head(10)

,Customer_ID,Passenger_Name,Age,Gender,City,State,Country,Travel_Class,Loyalty_Status,Booking_Channel,Payment_Method,Baggage_Count,Customer_Rating,Frequent_Flyer_Points
0,1,Emily Smith,48.0,Female,New York,NY,USA,Business,Gold,Website,Debit Card,3,4.0,94338
1,2,David Brown,40.0,Male,London,LND,UK,Economy,Silver,Travel Agent,Wallet,1,2.0,19123
2,3,Sarah Williams,51.0,Male,Singapore,SG,Singapore,First Class,Gold,Mobile App,Credit Card,2,3.0,62079
3,4,Emily Chen,63.0,Female,Tokyo,TKY,Japan,Premium Economy,Basic,Third Party,Credit Card,1,5.0,9190
4,5,Rahul Johnson,38.0,Male,Mumbai,MH,India,Economy,Basic,Third Party,Credit Card,0,2.0,2674
5,6,Olivia Smith,38.0,Female,sydney,NSW,Australia,Premium Economy,Silver,Mobile App,Wallet,1,2.0,19941
6,7,John Johnson,64.0,Male,London,LND,UK,Premium Economy,Basic,Travel Agent,Credit Card,3,4.0,6940
7,8,Michael Brown,52.0,Female,Paris,IDF,France,Economy,Silver,Travel Agent,Credit Card,1,1.0,12018
8,9,Mei Martinez,35.0,Male,new york,NY,USA,Economy,Silver,Mobile App,PayPal,2,4.0,19312
9,10,John Rodriguez,49.0,Male,Berlin,BER,Germany,Premium Economy,NaN,Third Party,PayPal,4,2.0,14712

In [67]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 122500 entries, 0 to 122499
Data columns (total 14 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   Customer_ID            122500 non-null  int64
 1   Passenger_Name         122500 non-null  str
 2   Age                    117408 non-null  float64
 3   Gender                 122500 non-null  str
 4   City                   122500 non-null  str
 5   State                  122500 non-null  str
 6   Country                122500 non-null  str
 7   Travel_Class           122500 non-null  str
 8   Loyalty_Status         120454 non-null  str
 9   Booking_Channel        122500 non-null  str
 10  Payment_Method         122500 non-null  str
 11  Baggage_Count          122500 non-null  int64
 12  Customer_Rating        120974 non-null  float64
 13  Frequent_Flyer_Points  122500 non-null  int64
dtypes: float64(2), int64(3), str(9)
memory usage: 13.1 MB

In [68]:
df.isnull().sum()

Customer_ID                 0
Passenger_Name              0
Age                      5092
Gender                      0
City                        0
State                       0
Country                     0
Travel_Class                0
Loyalty_Status           2046
Booking_Channel             0
Payment_Method              0
Baggage_Count               0
Customer_Rating          1526
Frequent_Flyer_Points       0
dtype: int64

In [69]:
df.duplicated().sum()

np.int64(2500)

In [70]:
df.head(5)

,Customer_ID,Passenger_Name,Age,Gender,City,State,Country,Travel_Class,Loyalty_Status,Booking_Channel,Payment_Method,Baggage_Count,Customer_Rating,Frequent_Flyer_Points
0,1,Emily Smith,48.0,Female,New York,NY,USA,Business,Gold,Website,Debit Card,3,4.0,94338
1,2,David Brown,40.0,Male,London,LND,UK,Economy,Silver,Travel Agent,Wallet,1,2.0,19123
2,3,Sarah Williams,51.0,Male,Singapore,SG,Singapore,First Class,Gold,Mobile App,Credit Card,2,3.0,62079
3,4,Emily Chen,63.0,Female,Tokyo,TKY,Japan,Premium Economy,Basic,Third Party,Credit Card,1,5.0,9190
4,5,Rahul Johnson,38.0,Male,Mumbai,MH,India,Economy,Basic,Third Party,Credit Card,0,2.0,2674

In [71]:
df.columns=df.columns.str.lower().str.strip()

In [72]:
df.head(5)

,customer_id,passenger_name,age,gender,city,state,country,travel_class,loyalty_status,booking_channel,payment_method,baggage_count,customer_rating,frequent_flyer_points
0,1,Emily Smith,48.0,Female,New York,NY,USA,Business,Gold,Website,Debit Card,3,4.0,94338
1,2,David Brown,40.0,Male,London,LND,UK,Economy,Silver,Travel Agent,Wallet,1,2.0,19123
2,3,Sarah Williams,51.0,Male,Singapore,SG,Singapore,First Class,Gold,Mobile App,Credit Card,2,3.0,62079
3,4,Emily Chen,63.0,Female,Tokyo,TKY,Japan,Premium Economy,Basic,Third Party,Credit Card,1,5.0,9190
4,5,Rahul Johnson,38.0,Male,Mumbai,MH,India,Economy,Basic,Third Party,Credit Card,0,2.0,2674

In [73]:
df.describe()

,customer_id,age,baggage_count,customer_rating,frequent_flyer_points
count,122500.000000,117408.000000,122500.000000,120974.000000,122500.000000
mean,59973.354620,41.914180,1.449837,3.004918,25000.370865
std,34642.989755,24.235678,1.145191,1.413670,30230.884909
min,1.000000,-20.000000,0.000000,1.000000,0.000000
25%,29976.000000,32.000000,1.000000,2.000000,8844.000000
50%,59943.500000,42.000000,1.000000,3.000000,17723.000000
75%,89961.250000,51.000000,2.000000,4.000000,26232.000000
max,120000.000000,999.000000,4.000000,5.000000,199974.000000

In [74]:
df.loc[df['age'] <= 0, 'age'] = np.nan
df.loc[df['age'] > 100, 'age'] = np.nan

In [75]:
df['age'] = df['age'].fillna(df['age'].mean())

In [76]:
df.describe()

,customer_id,age,baggage_count,customer_rating,frequent_flyer_points
count,122500.000000,122500.000000,122500.000000,120974.000000,122500.000000
mean,59973.354620,41.602444,1.449837,3.004918,25000.370865
std,34642.989755,13.588079,1.145191,1.413670,30230.884909
min,1.000000,1.000000,0.000000,1.000000,0.000000
25%,29976.000000,33.000000,1.000000,2.000000,8844.000000
50%,59943.500000,41.602444,1.000000,3.000000,17723.000000
75%,89961.250000,50.000000,2.000000,4.000000,26232.000000
max,120000.000000,100.000000,4.000000,5.000000,199974.000000

In [77]:
df.isnull().sum()

customer_id                 0
passenger_name              0
age                         0
gender                      0
city                        0
state                       0
country                     0
travel_class                0
loyalty_status           2046
booking_channel             0
payment_method              0
baggage_count               0
customer_rating          1526
frequent_flyer_points       0
dtype: int64

In [78]:
df['loyalty_status'] = df['loyalty_status'].fillna("Unknwown")
df['customer_rating'] = df['customer_rating'].fillna (df['customer_rating'].mode()[0])

In [79]:
df.isnull().sum()

customer_id              0
passenger_name           0
age                      0
gender                   0
city                     0
state                    0
country                  0
travel_class             0
loyalty_status           0
booking_channel          0
payment_method           0
baggage_count            0
customer_rating          0
frequent_flyer_points    0
dtype: int64

In [80]:
df.head(5)

,customer_id,passenger_name,age,gender,city,state,country,travel_class,loyalty_status,booking_channel,payment_method,baggage_count,customer_rating,frequent_flyer_points
0,1,Emily Smith,48.0,Female,New York,NY,USA,Business,Gold,Website,Debit Card,3,4.0,94338
1,2,David Brown,40.0,Male,London,LND,UK,Economy,Silver,Travel Agent,Wallet,1,2.0,19123
2,3,Sarah Williams,51.0,Male,Singapore,SG,Singapore,First Class,Gold,Mobile App,Credit Card,2,3.0,62079
3,4,Emily Chen,63.0,Female,Tokyo,TKY,Japan,Premium Economy,Basic,Third Party,Credit Card,1,5.0,9190
4,5,Rahul Johnson,38.0,Male,Mumbai,MH,India,Economy,Basic,Third Party,Credit Card,0,2.0,2674

In [81]:
df.nunique()

customer_id              120000
passenger_name              252
age                          99
gender                        6
city                         22
state                        11
country                      10
travel_class                 16
loyalty_status                5
booking_channel               4
payment_method                4
baggage_count                 5
customer_rating               5
frequent_flyer_points     44448
dtype: int64

In [82]:
df['gender'].unique()

<StringArray>
['Female', 'Male', 'F', 'Non-Binary', 'M', 'Prefer not to say']
Length: 6, dtype: str

In [83]:
df['gender'] = df['gender'].replace({'M':'Male', 'F':'Female', 'Non-Binary':'Unknown'})

In [84]:
df['gender'].unique()

<StringArray>
['Female', 'Male', 'Unknown', 'Prefer not to say']
Length: 4, dtype: str

In [85]:
df['city'].unique()

<StringArray>
[   'New York',      'London',   'Singapore',       'Tokyo',      'Mumbai',
      'sydney',       'Paris',    'new york',      'Berlin',       'Dubai',
     'Toronto',      'Sydney', 'Los Angeles', 'los angeles',      'london',
       'paris',       'tokyo',      'mumbai',   'singapore',       'dubai',
      'berlin',     'toronto']
Length: 22, dtype: str

In [86]:
df['city']=df['city'].str.title()

In [87]:
df['city'].unique()

<StringArray>
[   'New York',      'London',   'Singapore',       'Tokyo',      'Mumbai',
      'Sydney',       'Paris',      'Berlin',       'Dubai',     'Toronto',
 'Los Angeles']
Length: 11, dtype: str

In [88]:
df['state'].unique()

<StringArray>
['NY', 'LND', 'SG', 'TKY', 'MH', 'NSW', 'IDF', 'BER', 'DXB', 'ON', 'CA']
Length: 11, dtype: str

In [89]:
df['country'].unique()

<StringArray>
[      'USA',        'UK', 'Singapore',     'Japan',     'India', 'Australia',
    'France',   'Germany',       'UAE',    'Canada']
Length: 10, dtype: str

In [93]:

df['travel_class']=df['travel_class'].str.title().str.strip()
df['travel_class'].unique()

<StringArray>
['Business', 'Economy', 'First Class', 'Premium Economy']
Length: 4, dtype: str

In [92]:
df['loyalty_status'].unique()

<StringArray>
['Gold', 'Silver', 'Basic', 'Unknwown', 'Platinum']
Length: 5, dtype: str

In [94]:
df['booking_channel'].unique()

<StringArray>
['Website', 'Travel Agent', 'Mobile App', 'Third Party']
Length: 4, dtype: str

In [95]:
df.head(5)

,customer_id,passenger_name,age,gender,city,state,country,travel_class,loyalty_status,booking_channel,payment_method,baggage_count,customer_rating,frequent_flyer_points
0,1,Emily Smith,48.0,Female,New York,NY,USA,Business,Gold,Website,Debit Card,3,4.0,94338
1,2,David Brown,40.0,Male,London,LND,UK,Economy,Silver,Travel Agent,Wallet,1,2.0,19123
2,3,Sarah Williams,51.0,Male,Singapore,SG,Singapore,First Class,Gold,Mobile App,Credit Card,2,3.0,62079
3,4,Emily Chen,63.0,Female,Tokyo,TKY,Japan,Premium Economy,Basic,Third Party,Credit Card,1,5.0,9190
4,5,Rahul Johnson,38.0,Male,Mumbai,MH,India,Economy,Basic,Third Party,Credit Card,0,2.0,2674

In [96]:
df.describe()

,customer_id,age,baggage_count,customer_rating,frequent_flyer_points
count,122500.000000,122500.000000,122500.000000,122500.000000,122500.000000
mean,59973.354620,41.602444,1.449837,2.992400,25000.370865
std,34642.989755,13.588079,1.145191,1.409252,30230.884909
min,1.000000,1.000000,0.000000,1.000000,0.000000
25%,29976.000000,33.000000,1.000000,2.000000,8844.000000
50%,59943.500000,41.602444,1.000000,3.000000,17723.000000
75%,89961.250000,50.000000,2.000000,4.000000,26232.000000
max,120000.000000,100.000000,4.000000,5.000000,199974.000000

In [97]:
df.tail(5)

,customer_id,passenger_name,age,gender,city,state,country,travel_class,loyalty_status,booking_channel,payment_method,baggage_count,customer_rating,frequent_flyer_points
122495,23813,Michael Brown,49.0,Female,Los Angeles,CA,USA,Economy,Silver,Mobile App,PayPal,1,5.0,25295
122496,71042,John Johnson,34.0,Male,Sydney,NSW,Australia,Economy,Basic,Third Party,Wallet,1,5.0,4450
122497,98302,Alex Miller,51.0,Male,Singapore,SG,Singapore,First Class,Gold,Mobile App,Credit Card,4,2.0,97810
122498,14967,Michael Chen,42.0,Female,Dubai,DXB,UAE,Economy,Silver,Travel Agent,Credit Card,0,1.0,20497
122499,10555,Mei Patel,56.0,Female,Toronto,ON,Canada,Economy,Unknwown,Website,Credit Card,0,1.0,25423

In [98]:
df.isnull().sum()

customer_id              0
passenger_name           0
age                      0
gender                   0
city                     0
state                    0
country                  0
travel_class             0
loyalty_status           0
booking_channel          0
payment_method           0
baggage_count            0
customer_rating          0
frequent_flyer_points    0
dtype: int64

In [102]:
df.duplicated().sum()

np.int64(2500)

In [104]:
df['age']=df['age'].astype(int)

In [106]:
df.drop_duplicates(inplace=True)

In [108]:
df.to_csv('cleaned_passengers_1.csv', index=False)